apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxtest-dev
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: dev
  project: default
  source:
    path: kubernetes/applications/dev-k8s.ka8s.yaml
    repoURL: https://github.com/do0p/kubetraining.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground