apiVersion: v1
kind: Service
metadata:
  name: pod-info-service
  labels:
    app: pod-info
spec:
  selector:
    app: pod-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: podinfo
  type: ClusterIP