name: infra cdk8s workflow
on:
  pull_request:
    paths:
      - 'cdk8s/**'
  push:
    branches:
      - main
    paths:
      - 'cdk8s/**'
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y npm

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Setup NPM
        run: |
          npm install -g npm@10.2.4
          npm --version
        shell: bash          

      - name: Cdk8s Synth
        working-directory: 'cdk8s'
        run: |
          if [[ -f package-lock.json ]]; then
            npm ci
          else
            npm install
          fi
          npm run synth
        shell: bash

      - name: push
        run: |
          git status
          git add kubernetes/applications
          git commit -m "[SKIP CI] K8s manifest yaml files are created/updated"
          git push
        shell: bash      